{ pkgs, ... }:

{
  imports = [
    ../../home/common.nix
    ../../home/darwin.nix
    ../../home/modules/granted.nix
    ../../home/modules/aws.nix
  ];

  home.username = "julius.blank";
  home.homeDirectory = "/Users/julius.blank";

  # --- Git identity isolation ---
  #
  # Default identity (personal) comes from common.nix and applies to all repos
  # that don't match a more specific includeIf rule. Canonical clone for this repo
  # on both macOS hosts: ~/github/juliusblank/nix-configs (outside ~/work/) so this
  # repo uses personal identity; only repos under ~/work/ get the work override below.
  #
  # Work repos under ~/work/ get the work identity + work signing key.
  # The work signing key is looked up by its public key string — 1Password
  # matches it to the corresponding private key automatically.
  #
  # To get the public key string:
  #   1. Open 1Password → find "github ssh key" in Private vault
  #   2. Copy the public key (starts with "ssh-ed25519 AAAA...")
  #   3. Paste it below, prefixed with "key::"
  programs.git.includes = [
    {
      condition = "gitdir:~/work/";
      contents = {
        user = {
          name = "Julius Blank";
          email = "julius.blank@taktile.com";
          # TODO: paste work SSH public key from 1Password item "github ssh key"
          # signingkey = "key::ssh-ed25519 AAAA...";
        };
        gpg.format = "ssh";
        commit.gpgsign = true;
      };
    }
  ];

  # --- 1Password SSH agent ---
  #
  # Controls which SSH keys the 1Password agent exposes to this machine.
  # Keys are referenced by item name + vault. The agent serves the private
  # key to SSH/git; only the item name is configured here (no secrets).
  #
  # Isolation model:
  #   - "github ssh key" (Private vault) → work GitHub access + commit signing
  #   - "serenity" (Private vault) → personal repos (nix-configs, blog, etc.)
  #
  # Repos that should NOT be accessible from the work machine (DJ tooling,
  # purely private projects) should use a different SSH key that is not
  # listed here.
  home.file.".config/1password/ssh/agent.toml".text = ''
    # Work SSH key — used for work GitHub repos and commit signing
    [[ssh-keys]]
    item = "github ssh key"
    vault = "Private"

    # Personal SSH key — grants access to personal repos that are useful
    # in a work context (nix-configs, blog, etc.)
    [[ssh-keys]]
    item = "serenity"
    vault = "Private"
  '';

  home.packages = with pkgs; [
    # work-specific CLI tools go here
  ];

  # Granted for AWS credential management
  custom.granted.enable = true;

  # AWS CLI profiles — config is generated by a work CI workflow;
  # placeholder profile declared here for the module to be active.
  # TODO: integrate work-generated AWS config (separate task)
  custom.aws = {
    enable = true;
    profiles = [
      {
        name = "tktliam";
      }
    ];
  };
}
